# Generated by Django 3.0.8 on 2020-07-05 03:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the group name', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the error name', max_length=50)),
                ('description', models.TextField(help_text='Describe the error')),
                ('origin', models.TextField(help_text='Describe the error origin', max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('details', models.TextField(help_text='Enter the error details')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name', max_length=50)),
                ('email', models.CharField(help_text='Enter your email', max_length=254)),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Enter you password')),
            ],
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorInstances',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this error', primary_key=True, serialize=False)),
                ('level', models.CharField(blank=True, choices=[('C', 'Critical'), ('D', 'Debug'), ('E', 'Error'), ('W', 'Warning'), ('I', 'Info')], default='E', help_text='Choose the error level', max_length=20)),
                ('events', models.IntegerField(help_text='Enter the error code', max_length=20)),
                ('type_error', models.CharField(help_text='Choose the error type', max_length=20)),
                ('shelved', models.NullBooleanField()),
                ('error', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Log')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.User')),
            ],
        ),
    ]
