# Generated by Django 2.2.14 on 2020-07-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200705_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorinstances',
            name='type_error',
            field=models.CharField(blank=True, choices=[('dev', 'desenvolvedor'), ('hom', 'homolgação'), ('prod', 'produção')], default='dev', help_text='Choose the error type', max_length=20),
        ),
    ]
